"""Agent-facing client, service, and task helpers for TerraFin."""

from .service.client import TerraFinAgentClient
from .contracts.definitions import (
    DEFAULT_HOSTED_AGENT_DESCRIPTION,
    DEFAULT_HOSTED_AGENT_NAME,
    TerraFinAgentDefinition,
    TerraFinAgentDefinitionRegistry,
    build_default_agent_definition_registry,
    build_guru_agent_definitions,
)
from .guru import (
    GuruResearchMemo,
    GuruRoutePlan,
    run_guru_consult,
)
from .runtime import (
    TerraFinAgentApprovalRequiredError,
    TerraFinAgentContext,
    TerraFinAgentPolicyError,
    TerraFinAgentSession,
    TerraFinArtifact,
    TerraFinCapability,
    TerraFinCapabilityRegistry,
    TerraFinConversationMessage,
    TerraFinHostedAgentLoop,
    TerraFinHostedAgentRuntime,
    TerraFinHostedConversation,
    TerraFinHostedModelClient,
    TerraFinHostedRunResult,
    TerraFinModelTurn,
    TerraFinTaskRecord,
    TerraFinTaskRegistry,
    TerraFinToolCall,
    build_default_capability_registry,
    build_default_system_prompt,
    create_agent_context,
)
from .models.runtime import (
    TerraFinModelConfigError,
    TerraFinModelProvider,
    TerraFinModelProviderRegistry,
    TerraFinModelResponseError,
    TerraFinProviderRoutedModelClient,
    TerraFinRuntimeModel,
)
from .models.providers.openai import (
    TerraFinOpenAIConfigError,
    TerraFinOpenAIModelConfig,
    TerraFinOpenAIResponseError,
    TerraFinOpenAIResponsesModelClient,
)
from .models.providers import (
    TerraFinGithubCopilotConfig,
    TerraFinGithubCopilotConfigError,
    TerraFinGithubCopilotResponseError,
    TerraFinGithubCopilotResponsesProvider,
    TerraFinGoogleModelConfig,
    TerraFinGoogleModelConfigError,
    TerraFinGoogleModelResponseError,
    TerraFinGoogleResponsesProvider,
    TerraFinOpenAIResponsesProvider,
)
from .service import TerraFinAgentService
from .service.client_helpers import TerraFinRuntimeSessionClient, ask_agent, create_runtime_session
from .storage import (
    HostedSessionIndexEntry,
    HostedSessionStore,
    HostedTranscriptReader,
    HostedTranscriptStore,
    InMemoryHostedSessionStore,
    SQLiteHostedSessionStore,
    TerraFinHostedApprovalRequest,
    TerraFinHostedPermissionEvent,
    TerraFinHostedSessionRecord,
    TerraFinHostedViewContextRecord,
)
from .cli.tasks import (
    calendar_scan,
    compare_assets,
    macro_context,
    market_snapshot,
    open_chart,
    portfolio_context,
    stock_fundamentals,
    ticker_brief,
)
from .tools import (
    TerraFinHostedToolAdapter,
    TerraFinToolDefinition,
    TerraFinToolInvocationResult,
)


__all__ = [
    "TerraFinAgentClient",
    "TerraFinAgentService",
    "DEFAULT_HOSTED_AGENT_NAME",
    "DEFAULT_HOSTED_AGENT_DESCRIPTION",
    "TerraFinAgentDefinition",
    "TerraFinAgentDefinitionRegistry",
    "TerraFinHostedAgentRuntime",
    "TerraFinAgentPolicyError",
    "TerraFinAgentApprovalRequiredError",
    "TerraFinHostedAgentLoop",
    "TerraFinHostedConversation",
    "TerraFinHostedRunResult",
    "TerraFinHostedModelClient",
    "TerraFinConversationMessage",
    "TerraFinModelTurn",
    "TerraFinToolCall",
    "build_default_system_prompt",
    "TerraFinRuntimeModel",
    "TerraFinModelProvider",
    "TerraFinModelProviderRegistry",
    "TerraFinProviderRoutedModelClient",
    "TerraFinModelConfigError",
    "TerraFinModelResponseError",
    "TerraFinOpenAIModelConfig",
    "TerraFinOpenAIResponsesModelClient",
    "TerraFinOpenAIResponsesProvider",
    "TerraFinOpenAIConfigError",
    "TerraFinOpenAIResponseError",
    "TerraFinGoogleModelConfig",
    "TerraFinGoogleModelConfigError",
    "TerraFinGoogleModelResponseError",
    "TerraFinGoogleResponsesProvider",
    "TerraFinGithubCopilotConfig",
    "TerraFinGithubCopilotConfigError",
    "TerraFinGithubCopilotResponseError",
    "TerraFinGithubCopilotResponsesProvider",
    "TerraFinHostedToolAdapter",
    "TerraFinToolDefinition",
    "TerraFinToolInvocationResult",
    "TerraFinCapability",
    "TerraFinCapabilityRegistry",
    "TerraFinAgentSession",
    "TerraFinAgentContext",
    "TerraFinTaskRegistry",
    "TerraFinTaskRecord",
    "TerraFinArtifact",
    "HostedSessionIndexEntry",
    "HostedSessionStore",
    "HostedTranscriptReader",
    "HostedTranscriptStore",
    "InMemoryHostedSessionStore",
    "SQLiteHostedSessionStore",
    "TerraFinHostedApprovalRequest",
    "TerraFinHostedPermissionEvent",
    "TerraFinHostedSessionRecord",
    "TerraFinHostedViewContextRecord",
    "build_default_agent_definition_registry",
    "build_guru_agent_definitions",
    "build_default_capability_registry",
    "create_agent_context",
    "TerraFinRuntimeSessionClient",
    "create_runtime_session",
    "ask_agent",
    "ticker_brief",
    "market_snapshot",
    "compare_assets",
    "macro_context",
    "portfolio_context",
    "stock_fundamentals",
    "calendar_scan",
    "open_chart",
    "GuruResearchMemo",
    "GuruRoutePlan",
    "run_guru_consult",
]
